QuoteQuiz.RestServices/Controllers/PlayController.cs
namespace QuoteQuiz.RestServices.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System;
    using System.Net.Http;
    using Models.ViewModels;
    using System.Web.Mvc;

    public class PlayController : Controller
    {
        public PlayController()
        {
            this.HttpClient = new HttpClient();
        }

        private HttpClient HttpClient { get; }

        public ActionResult ChooseMode()
        {
            return this.View();
        }

        public ActionResult PlayBinary()
        {
            var host = GetHostLeftPart();
            var randomQuote = GetRandomQuoteFromDb(host);
            var quoteId = randomQuote.Id;

            var quoteAuthor = GetQuoteAuthorFromDb(quoteId, host);
            var randomPerson = GetRandomPersonFromDb(host);

            var people = new List<PersonViewModel>() {quoteAuthor, randomPerson};
            var shuffledPeople = Shuffle(people).ToList();
            var defaultIndex = 0;
            var chosenRandomPerson = shuffledPeople[defaultIndex];

            bool isCorrect = chosenRandomPerson.Name.Equals(randomQuote.PersonName);
            var binaryPlayViewModel = new BinaryPlayViewModel()
            {
                Person = chosenRandomPerson,
                Quote = randomQuote,
                Correct = isCorrect
            };

            return this.View(binaryPlayViewModel);
        }

        public ActionResult PlayMultiple()
        {
            var host = GetHostLeftPart();
            var randomQuote = GetRandomQuoteFromDb(host);
            var quoteId = randomQuote.Id;

            var quoteAuthor = GetQuoteAuthorFromDb(quoteId, host);
            var randomPerson = GetRandomPersonNotAuthorOfQuoteFromDb(quoteId, host);
            int randomPersonId = randomPerson.Id;
            var secondRandomPerson = GetRandomPersonNotAuthorOfQuoteFromDb(quoteId, host, randomPersonId);

            var people = new List<PersonViewModel> {quoteAuthor, randomPerson, secondRandomPerson};
            
            var multipleAnswersPlayViewModel = new MultipleAnswersPlayViewModel()
            {
                Quote = randomQuote,
                People = Shuffle(people)
            };

            return this.View(multipleAnswersPlayViewModel);
        }

        private PersonViewModel GetRandomPersonFromDb(string host)
        {
            var randomPersonHttpResponse = this.HttpClient.GetAsync(host + "/api/people/person").Result;
            var randomPerson = randomPersonHttpResponse.Content.ReadAsAsync<PersonViewModel>().Result;

            return randomPerson;
        }

        private PersonViewModel GetQuoteAuthorFromDb(int quoteId, string host)
        {
            var quoteAuthorHttpResponse = this.HttpClient.GetAsync(host + "/api/people/author/" + quoteId).Result;
            var quoteAuthor = quoteAuthorHttpResponse.Content.ReadAsAsync<PersonViewModel>().Result;

            return quoteAuthor;
        }

        private QuoteViewModel GetRandomQuoteFromDb(string host)
        {
            var randomQuoteHttpResponse = this.HttpClient.GetAsync(host + "/api/quotes/randomQuote").Result;
            var randomQuote = randomQuoteHttpResponse.Content.ReadAsAsync<QuoteViewModel>().Result;

            return randomQuote;
        }

        private PersonViewModel GetRandomPersonNotAuthorOfQuoteFromDb(int quoteId, string host, int? randomPersonId = null)
        {
            string randomPersonIdString = "";
            if (randomPersonId != null)
            {
                randomPersonIdString = randomPersonId.Value.ToString();
            }
            var randomPersonHttpResponse = this.HttpClient.GetAsync(host + "/api/people/person/" + quoteId + "/" + randomPersonIdString).Result;
            var randomPerson = randomPersonHttpResponse.Content.ReadAsAsync<PersonViewModel>().Result;

            return randomPerson;
        }

        // Fisher–Yates Shuffle Algorithm
        public IList<T> Shuffle<T>(IList<T> source)
        {
            Random rnd = new Random();
            var array = source.ToArray();
            var n = array.Length;
            for (var i = 0; i < n; i++)
            {
                int r = i + rnd.Next(0, n - i);
                var temp = array[i];
                array[i] = array[r];
                array[r] = temp;
            }

            return array;
        }

        private string GetHostLeftPart()
        {
            var host = Request.Url.GetLeftPart(UriPartial.Authority);

            return host;
        }
    }
}

QuoteQuiz.RestServices/Views/Play/ChooseMode.cshtml
@{
    ViewBag.Title = "Choose mode";
}

<h2>Choose Mode</h2>
<hr/>
@Html.ActionLink("Binary Mode", "PlayBinary", "Play", new { @class = "btn btn-info gray-x display-inline-block float-right margin-top-short" })
<hr/>
@Html.ActionLink("Multiple Choice", "PlayMultiple", "Play", new { @class = "btn btn-default gray-x display-inline-block float-right margin-top-short" })

QuoteQuiz.RestServices/Views/Play/PlayBinary.cshtml
@model QuoteQuiz.RestServices.Models.ViewModels.BinaryPlayViewModel

@{
    ViewBag.Title = "Famous Quote Quiz";
}

<p id="author" class="hidden">
    @Model.Quote.PersonName
</p>
<h2>Famous Quote Quiz</h2>
<div id="wrapper">
    <h4 id="gray-header">Who Said It?</h4>
    <div id="pink-background">
        <p id="quote-text">
            "@Model.Quote.Text "
        </p>
    </div>
    <div id="answer-box">
        <h5 id="gray-name">
            @Model.Person.Name
        </h5>
        <script>
            var author = document.getElementById('gray-name').innerHTML.trim();
        </script>
        <div>
            @if (Model.Correct)
            {
                <button id="yes" class="btn btn-success float-left-left button-binary" onclick="correctAnswer();">Yes</button>
                <button id="no" class="btn btn-danger float-right-right button-binary button-binary-red" onclick="wrongAnswer();">No</button>
            }
            else
            {
                <button id="yes" class="btn btn-success float-left-left button-binary" onclick="wrongAnswer();">Yes</button>
                <button id="no" class="btn btn-danger float-right-right button-binary button-binary-red" onclick="correctAnswer();">No</button>
            }
        </div>
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/sweetalert-master/dist/sweetalert.min.js"></script>
    <script>
        var quoteAuthor = document.getElementById('author').innerHTML.trim();
        var correct = @Model.Correct;

        function correctAnswer() {
            if (correct) {
                swal("Correct!", 'This quote is from ' + author + '.', "success");
                replaceAnswerBox();
            } else {
                swal("Correct!", 'This quote is from ' + quoteAuthor + '.', "success");
                replaceAnswerBox();
            }
        }

        function wrongAnswer() {
            if (correct) {
                sweetAlert("Sorry, you are wrong!", 'This quote is from ' + quoteAuthor + '.', "error");
                replaceAnswerBox();
            } else {
                sweetAlert("Sorry, you are wrong!", 'This quote is from ' + quoteAuthor + '.', "error");
                replaceAnswerBox();
            }
        }

        function replaceAnswerBox() {
            document.getElementById('answer-box').innerHTML = '<h4 id="green-name">' + quoteAuthor + '</h4><div class="text-align-centered">' +
                '@Html.ActionLink("Next", "PlayBinary", "Play", new { @class = "button-choice btn btn-primary gray-x display-inline-block margin-top-short" })</div>';
        }
    </script>
}

QuoteQuiz.RestServices/Views/Play/PlayMultiple.cshtml
@model QuoteQuiz.RestServices.Models.ViewModels.MultipleAnswersPlayViewModel

@{
    ViewBag.Title = "Famous Quote Quiz";
}

<p id="author" class="hidden">
    @Model.Quote.PersonName
</p>
<h2>Famous Quote Quiz</h2>
<div id="wrapper">
    <h4 id="gray-header">Who Said It?</h4>
    <div id="pink-background">
        <p id="quote-text">
            "@Model.Quote.Text "
        </p>
    </div>
    <div id="answer-box">
        @{
            var firstChoice = Model.People[0].Name;
            var secondChoice = Model.People[1].Name;
            var thirdChoice = Model.People[2].Name;
            var correctChoice = 0;
            for (int i = 0; i < Model.People.Count; i++)
            {
                var person = Model.People[i];
                if (person.Name.Equals(Model.Quote.PersonName))
                {
                    correctChoice = i + 1;
                }
            }
        }
        <p id="correct-choice" class="hidden">
            @correctChoice
        </p>

        <div class="gray-box">
            <a href="#" class="white-person-name" id="1">
                &nbsp;-> @firstChoice
            </a>
        </div>
        <div class="gray-box">
            <a href="#" class="white-person-name" id="2">
                &nbsp;-> @secondChoice
            </a>
        </div>
        <div class="gray-box">
            <a href="#" class="white-person-name" id="3">
                &nbsp;-> @thirdChoice
            </a>
        </div>
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/sweetalert-master/dist/sweetalert.min.js"></script>
    <script>
        function removeA(arr) {
            var what, a = arguments, L = a.length, ax;
            while (L > 1 && arr.length) {
                what = a[--L];
                while ((ax = arr.indexOf(what)) !== -1) {
                    arr.splice(ax, 1);
                }
            }
            return arr;
        }

        var quoteAuthor = document.getElementById('author').innerHTML.trim();
        var correctOption = document.getElementById('correct-choice').innerHTML.trim();
        var correctChoice = document.getElementById(correctOption).addEventListener("click", correctOptionClicked, false);
        var array = ['1', '2', '3'];
        removeA(array, correctOption);
        var firstIncorrect = array[0];
        var firstIncorrectChoice = document.getElementById(firstIncorrect).addEventListener("click", incorrectOptionClicked, false);
        var secondIncorrect = array[1];
        var secondIncorrectChoice = document.getElementById(secondIncorrect).addEventListener("click", incorrectOptionClicked, false);

        function correctOptionClicked() {
            swal("Correct!", 'This quote is from ' + quoteAuthor + '.', "success");
            replaceAnswerBox();
        }

        function incorrectOptionClicked() {
            sweetAlert("Sorry, you are wrong!", 'This quote is from ' + quoteAuthor + '.', "error");
            replaceAnswerBox();
        }

        function replaceAnswerBox() {
            document.getElementById('answer-box').innerHTML = '<h4 id="green-name">' + quoteAuthor + '</h4><div class="text-align-centered">' +
                '@Html.ActionLink("Next", "PlayMultiple", "Play", new { @class = "button-choice btn btn-primary gray-x display-inline-block margin-top-short" })</div>';
        }
    </script>
}